options(RCurlOptions = list(
  verbose = TRUE,
  proxy ="http://172.16.2.30:8080"))
options(rpubs.upload.method = "internal") 
# run the above line and restart the code

library(gmapsdistance)
library(rvest)

set.api.key("-----------------------------")
get.api.key()

# origin1=c("Malancha Vegetables Market, Dhekeya, Malancha, Kharagpur, West Bengal","Amigos, Kharagpur, West Bengal","Himalayan Delight, Kharagpur, West Bengal","Flavour, Kharagpur, West Bengal","Scrummys Kharagpur, Kharagpur, West Bengal","The Sheesha - Arabian Nights, Kharagpur, West Bengal","Hotel Park, Kharagpur, West Bengal","Hot Bite, Kharagpur, West Bengal","Hot & Spick, Pan Loop, IIT Kharagpur, Kharagpur, West Bengal","Askaan's Pizza Town, Kharagpur, West Bengal","Taaz Biryani, Kharagpur, West Bengal","Domino's Pizza, Kharagpur, West Bengal","Heritage Restaurant, Scholars Avenue, IIT Kharagpur, Kharagpur, West Bengal","Nawab Ali, Oval Park, Balihati, West Bengal")
# destination1=c("Rocky Fast Food Center, New Bitumen Road, IIT Kharagpur, Kharagpur","RadhaKrishnan Hall of Residence,New Bitumen Road, IIT Kharagpur, Kharagpur, West Bengal","VS Hall, IIT Kharagpur, Kharagpur, West Bengal","JCB, Kharagpur, West Bengal","Dr. B. R. Ambedkar Hall Of Residence, IIT Kharagpur, Kharagpur, West Bengal","LLR Hall of Residence,IIT Kharagpur,Kharagpur, West Bengal","LBS Hall, Kharagpur, West Bengal","Meghnad Saha Hall of Residence, IIT Kharagpur,Kharagpur, West Bengal","MMM Hall of Residence, Boundary Road, IIT Kharagpur, Kharagpur, West Bengal","ZH Hall,Kharagpur, West Bengal","MT hall of residance, IIT Kharagpur, Kharagpur, West Bengal","IG Hall, Kharagpur, West Bengal","SN Hall Of Residence, Kharagpur, West Bengal","B C Roy Hall of Residence,Kharagpur, West Bengal","Azad Hall of Residence, Pan Loop, IIT Kharagpur, Kharagpur, West Bengal","Patel Hallof Residence, Pan Loop, IIT Kharagpur, Kharagpur, West Bengal","Nehru Hall of Residence, Pan Loop, IIT Kharagpur, Kharagpur, West Bengal","HJB Hall of Residence, Scholars Avenue, IIT Kharagpur, Kharagpur, West Bengal","RLB Hall of Residence, Scholars Avenue, IIT Kharagpur, Kharagpur, West Bengal","Sister Nivedita Hall of Residence, Scholars Avenue, IIT Kharagpur, Kharagpur, West Bengal","VSRC Guest House, IIT Kharagpur, Kharagpur, West Bengal","Gokhale Hall Rd, IIT Kharagpur, Kharagpur, West Bengal","Technology Students' Gymkhana, Scholars Avenue, IIT Kharagpur, Kharagpur, West Bengal","Technology Guest House, Guest House Road, IIT Kharagpur, Kharagpur, West Bengal","sbi near IIT Kharagpur, Kharagpur, West Bengal","SAM Hall Garden, Scholars Avenue, IIT Kharagpur, Kharagpur, West Bengal","Tech Market, IIT Kharagpur, Kharagpur, West Bengal")
# origin1=c("Washington DC", "New York NY")
# destination1 = c("Los Angeles CA", "Austin TX")

# for sources
# origin1=c("Malancha Vegetables Market, Dhekeya, Malancha, Kharagpur, West Bengal","Amigos, Kharagpur, West Bengal","Himalayan Delight, Kharagpur, West Bengal","Flavour, Kharagpur, West Bengal","Scrummys Kharagpur, Kharagpur, West Bengal","The Sheesha - Arabian Nights, Kharagpur, West Bengal","Hotel Park, Kharagpur, West Bengal","Hot Bite, Kharagpur, West Bengal","Hot & Spick, Pan Loop, IIT Kharagpur, Kharagpur, West Bengal","Askaan's Pizza Town, Kharagpur, West Bengal","Taaz Biryani, Kharagpur, West Bengal","Domino's Pizza, Kharagpur, West Bengal","Heritage Restaurant, Scholars Avenue, IIT Kharagpur, Kharagpur, West Bengal","Nawab Ali, Oval Park, Balihati, West Bengal")
# destination1=c("Malancha Vegetables Market, Dhekeya, Malancha, Kharagpur, West Bengal","Amigos, Kharagpur, West Bengal","Himalayan Delight, Kharagpur, West Bengal","Flavour, Kharagpur, West Bengal","Scrummys Kharagpur, Kharagpur, West Bengal","The Sheesha - Arabian Nights, Kharagpur, West Bengal","Hotel Park, Kharagpur, West Bengal","Hot Bite, Kharagpur, West Bengal","Hot & Spick, Pan Loop, IIT Kharagpur, Kharagpur, West Bengal","Askaan's Pizza Town, Kharagpur, West Bengal","Taaz Biryani, Kharagpur, West Bengal","Domino's Pizza, Kharagpur, West Bengal","Heritage Restaurant, Scholars Avenue, IIT Kharagpur, Kharagpur, West Bengal","Nawab Ali, Oval Park, Balihati, West Bengal")

# for destination1
# origin1=c("Rocky Fast Food Center, New Bitumen Road, IIT Kharagpur, Kharagpur","RadhaKrishnan Hall of Residence,New Bitumen Road, IIT Kharagpur, Kharagpur, West Bengal","VS Hall, IIT Kharagpur, Kharagpur, West Bengal","JCB, Kharagpur, West Bengal","Dr. B. R. Ambedkar Hall Of Residence, IIT Kharagpur, Kharagpur, West Bengal","LLR Hall of Residence,IIT Kharagpur,Kharagpur, West Bengal","LBS Hall, Kharagpur, West Bengal","Meghnad Saha Hall of Residence, IIT Kharagpur,Kharagpur, West Bengal","MMM Hall of Residence, Boundary Road, IIT Kharagpur, Kharagpur, West Bengal","ZH Hall,Kharagpur, West Bengal","MT hall of residance, IIT Kharagpur, Kharagpur, West Bengal","IG Hall, Kharagpur, West Bengal","SN Hall Of Residence, Kharagpur, West Bengal","B C Roy Hall of Residence,Kharagpur, West Bengal","Azad Hall of Residence, Pan Loop, IIT Kharagpur, Kharagpur, West Bengal","Patel Hallof Residence, Pan Loop, IIT Kharagpur, Kharagpur, West Bengal")
# destination1=c("Rocky Fast Food Center, New Bitumen Road, IIT Kharagpur, Kharagpur","RadhaKrishnan Hall of Residence, New Bitumen Road, IIT Kharagpur, Kharagpur, West Bengal","VS Hall, IIT Kharagpur, Kharagpur, West Bengal","JCB, Kharagpur, West Bengal","Dr. B. R. Ambedkar Hall Of Residence, IIT Kharagpur, Kharagpur, West Bengal","LLR Hall of Residence, IIT Kharagpur,Kharagpur, West Bengal","LBS Hall, Kharagpur, West Bengal","Meghnad Saha Hall of Residence, IIT Kharagpur, Kharagpur, West Bengal","MMM Hall of Residence, Boundary Road, IIT Kharagpur, Kharagpur, West Bengal","ZH Hall, Kharagpur, West Bengal","MT hall of residance, IIT Kharagpur, Kharagpur, West Bengal","IG Hall, Kharagpur, West Bengal","SN Hall Of Residence, Kharagpur, West Bengal","B C Roy Hall of Residence,Kharagpur, West Bengal","Azad Hall of Residence, Pan Loop, IIT Kharagpur, Kharagpur, West Bengal","Patel Hallof Residence, Pan Loop, IIT Kharagpur, Kharagpur, West Bengal","Nehru Hall of Residence, Pan Loop, IIT Kharagpur, Kharagpur, West Bengal","HJB Hall of Residence, Scholars Avenue, IIT Kharagpur, Kharagpur, West Bengal","RLB Hall of Residence, Scholars Avenue, IIT Kharagpur, Kharagpur, West Bengal","Sister Nivedita Hall of Residence, Scholars Avenue, IIT Kharagpur, Kharagpur, West Bengal","VSRC Guest House, IIT Kharagpur, Kharagpur, West Bengal","Gokhale Hall Rd, IIT Kharagpur, Kharagpur, West Bengal","Technology Students' Gymkhana, Scholars Avenue, IIT Kharagpur, Kharagpur, West Bengal","Technology Guest House, Guest House Road, IIT Kharagpur, Kharagpur, West Bengal","sbi near IIT Kharagpur, Kharagpur, West Bengal","SAM Hall Garden, Scholars Avenue, IIT Kharagpur, Kharagpur, West Bengal","Tech Market, IIT Kharagpur, Kharagpur, West Bengal","Amigos, Kharagpur, West Bengal")

# for destination2
origin1=c("Nehru Hall of Residence, Pan Loop, IIT Kharagpur, Kharagpur, West Bengal","HJB Hall of Residence, Scholars Avenue, IIT Kharagpur, Kharagpur, West Bengal","RLB Hall of Residence, Scholars Avenue, IIT Kharagpur, Kharagpur, West Bengal","Sister Nivedita Hall of Residence, Scholars Avenue, IIT Kharagpur, Kharagpur, West Bengal","VSRC Guest House, IIT Kharagpur, Kharagpur, West Bengal","Gokhale Hall Rd, IIT Kharagpur, Kharagpur, West Bengal","Technology Students' Gymkhana, Scholars Avenue, IIT Kharagpur, Kharagpur, West Bengal","Technology Guest House, Guest House Road, IIT Kharagpur, Kharagpur, West Bengal","sbi near IIT Kharagpur, Kharagpur, West Bengal","SAM Hall Garden, Scholars Avenue, IIT Kharagpur, Kharagpur, West Bengal","Tech Market, IIT Kharagpur, Kharagpur, West Bengal","Amigos, Kharagpur, West Bengal")
destination1=c("Rocky Fast Food Center, New Bitumen Road, IIT Kharagpur, Kharagpur","RadhaKrishnan Hall of Residence, New Bitumen Road, IIT Kharagpur, Kharagpur, West Bengal","VS Hall, IIT Kharagpur, Kharagpur, West Bengal","JCB, Kharagpur, West Bengal","Dr. B. R. Ambedkar Hall Of Residence, IIT Kharagpur, Kharagpur, West Bengal","LLR Hall of Residence, IIT Kharagpur,Kharagpur, West Bengal","LBS Hall, Kharagpur, West Bengal","Meghnad Saha Hall of Residence, IIT Kharagpur, Kharagpur, West Bengal","MMM Hall of Residence, Boundary Road, IIT Kharagpur, Kharagpur, West Bengal","ZH Hall, Kharagpur, West Bengal","MT hall of residance, IIT Kharagpur, Kharagpur, West Bengal","IG Hall, Kharagpur, West Bengal","SN Hall Of Residence, Kharagpur, West Bengal","B C Roy Hall of Residence,Kharagpur, West Bengal","Azad Hall of Residence, Pan Loop, IIT Kharagpur, Kharagpur, West Bengal","Patel Hallof Residence, Pan Loop, IIT Kharagpur, Kharagpur, West Bengal","Nehru Hall of Residence, Pan Loop, IIT Kharagpur, Kharagpur, West Bengal","HJB Hall of Residence, Scholars Avenue, IIT Kharagpur, Kharagpur, West Bengal","RLB Hall of Residence, Scholars Avenue, IIT Kharagpur, Kharagpur, West Bengal","Sister Nivedita Hall of Residence, Scholars Avenue, IIT Kharagpur, Kharagpur, West Bengal","VSRC Guest House, IIT Kharagpur, Kharagpur, West Bengal","Gokhale Hall Rd, IIT Kharagpur, Kharagpur, West Bengal","Technology Students' Gymkhana, Scholars Avenue, IIT Kharagpur, Kharagpur, West Bengal","Technology Guest House, Guest House Road, IIT Kharagpur, Kharagpur, West Bengal","sbi near IIT Kharagpur, Kharagpur, West Bengal","SAM Hall Garden, Scholars Avenue, IIT Kharagpur, Kharagpur, West Bengal","Tech Market, IIT Kharagpur, Kharagpur, West Bengal","Amigos, Kharagpur, West Bengal")

origin <- gsub(" ","+",origin1)
destination <- gsub(" ","+",destination1)
results = gmapsdistance(origin,destination,mode = "driving")

library(xlsx)
write.xlsx(results, "distancedest2.xlsx", sheetName="Sheet1")
